version: "3"
services:
  dispenser-fork:
    image: dispenser-fork
    build: .
    container_name: dispenser-fork
    restart: unless-stopped
    environment:
      #DO NOT CHANGE THE HOST
      POSTGRES_HOST: db
      #DO NOT CHANGE THIS UNLESS YOU KNOW WHAT YOU ARE DOING
      POSTGRES_USER: dispenser-fork 
      #CHANGE THE PASSWORD TO SOMETHING MORE SECURE (RECOMMENDED)
      POSTGRES_PASSWORD: postgres
      #DO NOT CHANGE THIS UNLESS YOU KNOW WHAT YOU ARE DOING!! 
      POSTGRES_DB: dispenser-fork
      #THIS SHOULDN'T NEED TO CHANGE
      DATABASE_URL: postgres://dispenser-fork:postgres@db:5432/dispenser-fork
      ####
      #ANYTHING BELOW THIS NEEDS TO BE EDITED
      #The discord bot's token (REQUIRED)
      TOKEN: token
      #The Bot ID for slash command deployment (REQUIRED)
      CLIENT_ID: clientID
      #The Server ID for quick deployment (Not required but recommended for quick deployment, delete line to disable)
      GUILD_ID: guildID
      # The ID of the Bot owner (NOT REQUIRED, delete line to disable)
      OWNER_ID: ownerID
      # Cooldown time in ms (set to 0 to disable)
      COOLDOWN_TIME: 2000
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: dispenser-fork-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: dispenser-fork
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dispenser-fork 
    volumes:
      - ./db:/var/lib/postgresql/data 
networks:
  default:
    external: false
    name: dispenser-fork-network
